server:
  port: 8180
  servlet:
    context-path: /app
spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lightcrm?currentSchema=public
    username: postgres
    password: <password>
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
jwt:
  secret: yW5t5wKaayfiU3J5PIkobDACPSuWiHx1MdM1g0MdFE9AcI8Hc2b5hlLCJvDiawkeYycLOCHdYUXnnnKJ